Update GitHub Actions
cego/container-manager pull request #21
Opened 2024-02-27 14:01 UTC by staal0

2024-02-27 15:10 UTC, SlyngDK requested changes

2024-02-27 15:10 UTC, SlyngDK commented on .github/workflows/release.yml
> +
```suggestion
```

2024-02-27 15:10 UTC, SlyngDK commented on .github/workflows/package.yml
> +      #   run: go test -v ./...
```suggestion

```

2024-02-27 19:28 UTC, firecow submitted a review, later dismissed
LGTM

2024-02-28 07:36 UTC, firecow approved these changes

2024-02-28 07:42 UTC, firecow approved these changes
LGTM

2024-02-28 08:49 UTC, merged