Attach/detach to network
cego/container-manager pull request #25
Opened 2024-03-18 08:39 UTC by staal0

Detach from networks that only has Container-managers own containers.
This also adds attach to networks and is now done without triggering a docker restart.

2024-03-19 06:36 UTC, firecow approved these changes
I have a single suggestion to a comment. Other than that, looks good to me.

2024-03-19 06:36 UTC, firecow commented on main.go
> +		// If more than 0 containers in a network, then add config containers to the network
```suggestion
		// If more than 0 containers in a network excluding containers from config, then add containers in config to the network
```

2024-03-19 06:39 UTC, firecow reviewed
Maybe configNames is a bit misleading. Renaming to containerNames

2024-03-19 06:39 UTC, firecow commented on main.go
> +	networkNames, err := m.getNetworkNames(configNames)
```suggestion
	containerNames := []string{}
	for _, c := range config.Containers {
		containerNames = append(containerNames, c.Name)
	}

	networkNames, err := m.getNetworkNames(containerNames)
```

2024-03-19 06:39 UTC, firecow commented on main.go
> +func (m *manager) getNetworkNames(configNames []string) ([]string, error) {
```suggestion
func (m *manager) getNetworkNames(containerNames []string) ([]string, error) {
```

2024-03-19 06:39 UTC, firecow commented on main.go
> +		}
```suggestion
		// Inspect each network to get attached containers
		attached, err := m.cli.NetworkInspect(m.ctx, network.Name, types.NetworkInspectOptions{})
		if err != nil {
			return nil, err
		}

		for _, container := range attached.Containers {
			if containsString(containerNames, container.Name) && network.Name != "bridge" {
				// Detach from network if config containers is the only ones
				if (len(attached.Containers) - len(containerNames)) == 0 {
					m.detachNetwork(network.Name, container.Name)
				}
			}
		}
```

2024-03-19 06:39 UTC, firecow commented on main.go
> +				for _, container := range configNames {
```suggestion
				for _, container := range containerNames {
```

2024-03-20 08:35 UTC, SlyngDK requested changes

2024-03-20 08:35 UTC, SlyngDK commented on main.go
> +				if (len(attached.Containers) - len(containerNames)) == 0 {
I don't think your count always will be correct, as there can be containers not attaching to any extra networks.

2024-03-20 08:35 UTC, SlyngDK commented on main.go
> +func (m *manager) getNetworkNames(containerNames []string) ([]string, error) {
This function is original designed to return networks applicable, to attach for all networks. Not attaching or detaching directly, that is handlede later.

2024-04-02 08:20 UTC, SlyngDK requested changes

2024-04-02 08:20 UTC, SlyngDK commented on main.go
>  		}
```suggestion
		for _, endpoint := range attached.Containers {
			if !containsString(containerNames, endpoint.Name) &&
				(network.Attachable || network.Scope == "local") &&
				!containsString(ignoredNetworkNames, network.Name) {
				names = append(names, network.Name)
				break
			}
		}
```
I think this is simpler.

2024-04-02 13:55 UTC, SlyngDK approved these changes

2024-04-03 06:15 UTC, merged